"use client"
import { ApolloClient, ApolloProvider, InMemoryCache } from '@apollo/client';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import App from 'next/app';

const inter = Inter({ subsets: ['latin'] })
const client = new ApolloClient({
  cache: new InMemoryCache(),
  uri: 'http://localhost:4000',
});
console.log(client)
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      root.reder( 
        <ApolloProvider client={client}>
        {children}
        </ApolloProvider>
      )
      
  
      
    </html>
  )
}
