"use client";
import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import App from "next/app";

const inter = Inter({ subsets: ["latin"] });
const client = new ApolloClient({
  cache: new InMemoryCache(),
  uri: "http://localhost:4000",
  headers: {
    authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBydWViYUBwcnVlYmEuY29tIiwiaWQiOiI2NGQ2ODc3MDM0Nzk1ZDI4NDI4NGEyOTUiLCJpYXQiOjE2OTE3ODI2MjN9.jvv_rBhhEkyqx8tkHvww3yAsTEy3IyIGKVO7mW9S-d4",
    "Content-Type": "application/json",
  },
});
console.log(client);
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ApolloProvider client={client}>
        <body>{children}</body>
      </ApolloProvider>
    </html>
  );
}
