version: "3"

services:
  backend:
    build: .
    ports:
      - "3977:3977"
    depends_on:
      - db
    environment:
     - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
       - MONGO_INITDB_ROOT_USERNAME=admin
       - MONGO_INITDB_ROOT_PASSWORD=SocialUP
       - MONGO_INITDB_DATABASE=socialup-time