version: "3"

services:
  backend:
    build: ./src
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
       NODE_ENV: production
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    