on:
  push:
    branches:
      - main

name: CI - Build and Push Docker Images

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, Backed]
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v3
        # Only enable if cross-platform builds are required

      - name: Set up Docker Buildx (optional)
        uses: docker/setup-buildx-action@v3
        # Only enable if multi-arch builds are needed

      - name: Login to Docker Hub (securely)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        env:
          # Store credentials in a dedicated runner secret
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (per service)
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: davidjrosso/${{ matrix.service }}:${{ github.sha }}
          context: ./${{ matrix.service }}  # Build from specific directory

